name: ArmoredElytra
main: nl.pim16aap2.armoredElytra.ArmoredElytra
version: ${project.version}
author: pim16aap2
softdepend: [ AdvancedEnchantments ]
api-version: 1.13
commands:
  ArmoredElytra:
    description: Give an armored elytra of the specified tier.
    usage: /ArmoredElytra [receiver] <tier>
permissions:
  armoredelytra.wear.leather:
    description: Allow the player to wear leather tier armored elytras.
  armoredelytra.wear.gold:
    description: Allow the player to wear gold tier armored elytras.
  armoredelytra.wear.chain:
    description: Allow the player to wear chain tier armored elytras.
  armoredelytra.wear.iron:
    description: Allow the player to wear iron tier armored elytras.
  armoredelytra.wear.diamond:
    description: Allow the player to wear diamond tier armored elytras.
  armoredelytra.wear.netherite:
    description: Allow the player to wear netherite tier armored elytras.
  armoredelytra.craft.leather:
    description: Allow the player to craft leather tier armored elytras.
  armoredelytra.craft.gold:
    description: Allow the player to craft gold tier armored elytras.
  armoredelytra.craft.chain:
    description: Allow the player to craft chain tier armored elytras.
  armoredelytra.craft.iron:
    description: Allow the player to craft iron tier armored elytras.
  armoredelytra.craft.diamond:
    description: Allow the player to craft diamond tier armored elytras.
  armoredelytra.craft.netherite:
    description: Allow the player to craft netherite tier armored elytras.
  armoredelytra.give.leather:
    description: Allow the player to spawn in leather tier armored elytras.
  armoredelytra.give.gold:
    description: Allow the player to spawn in gold tier armored elytras.
  armoredelytra.give.chain:
    description: Allow the player to spawn in chain tier armored elytras.
  armoredelytra.give.iron:
    description: Allow the player to spawn in iron tier armored elytras.
  armoredelytra.give.diamond:
    description: Allow the player to spawn in diamond tier armored elytras.
  armoredelytra.give.netherite:
    description: Allow the player to spawn in netherite tier armored elytras.
  armoredElytra.admin:
    description: Receive a message if this plugin is out of date when joining the server.
